/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AttributionRouteImport } from './routes/attribution'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as KeysIndexRouteImport } from './routes/keys.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ModelsIdRouteImport } from './routes/models.$id'
import { Route as KeysIdRouteImport } from './routes/keys.$id'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionRoute = AttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIdRoute = ModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIdRoute = KeysIdRouteImport.update({
  id: '/keys/$id',
  path: '/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/config': typeof ConfigRoute
  '/endpoints': typeof EndpointsRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/system': typeof SystemRoute
  '/keys/$id': typeof KeysIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/keys/': typeof KeysIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/config': typeof ConfigRoute
  '/endpoints': typeof EndpointsRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/system': typeof SystemRoute
  '/keys/$id': typeof KeysIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/keys': typeof KeysIndexRoute
  '/models': typeof ModelsIndexRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/config': typeof ConfigRoute
  '/endpoints': typeof EndpointsRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/system': typeof SystemRoute
  '/keys/$id': typeof KeysIdRoute
  '/models/$id': typeof ModelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/keys/': typeof KeysIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attribution'
    | '/config'
    | '/endpoints'
    | '/logs'
    | '/playground'
    | '/policies'
    | '/system'
    | '/keys/$id'
    | '/models/$id'
    | '/requests/$id'
    | '/keys/'
    | '/models/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attribution'
    | '/config'
    | '/endpoints'
    | '/logs'
    | '/playground'
    | '/policies'
    | '/system'
    | '/keys/$id'
    | '/models/$id'
    | '/requests/$id'
    | '/keys'
    | '/models'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/attribution'
    | '/config'
    | '/endpoints'
    | '/logs'
    | '/playground'
    | '/policies'
    | '/system'
    | '/keys/$id'
    | '/models/$id'
    | '/requests/$id'
    | '/keys/'
    | '/models/'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionRoute: typeof AttributionRoute
  ConfigRoute: typeof ConfigRoute
  EndpointsRoute: typeof EndpointsRoute
  LogsRoute: typeof LogsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoliciesRoute: typeof PoliciesRoute
  SystemRoute: typeof SystemRoute
  KeysIdRoute: typeof KeysIdRoute
  ModelsIdRoute: typeof ModelsIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  KeysIndexRoute: typeof KeysIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribution': {
      id: '/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/': {
      id: '/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$id': {
      id: '/models/$id'
      path: '/models/$id'
      fullPath: '/models/$id'
      preLoaderRoute: typeof ModelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/$id': {
      id: '/keys/$id'
      path: '/keys/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof KeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionRoute: AttributionRoute,
  ConfigRoute: ConfigRoute,
  EndpointsRoute: EndpointsRoute,
  LogsRoute: LogsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoliciesRoute: PoliciesRoute,
  SystemRoute: SystemRoute,
  KeysIdRoute: KeysIdRoute,
  ModelsIdRoute: ModelsIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  KeysIndexRoute: KeysIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
